# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\"/\n\x0ePredictRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t\x12\x10\n\x08payloads\x18\x02 \x03(\x0c\",\n\x0fPredictResponse\x12\x0b\n\x03ids\x18\x01 \x03(\t\x12\x0c\n\x04prob\x18\x02 \x03(\x02\x32@\n\x0cModelService\x12\x30\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse(\x01\x30\x01\x42\x32Z0github.com/Imm0bilize/pkg/mlservice/api/proto/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/Imm0bilize/pkg/mlservice/api/proto/v1'
  _PREDICTREQUEST._serialized_start=20
  _PREDICTREQUEST._serialized_end=67
  _PREDICTRESPONSE._serialized_start=69
  _PREDICTRESPONSE._serialized_end=113
  _MODELSERVICE._serialized_start=115
  _MODELSERVICE._serialized_end=179
# @@protoc_insertion_point(module_scope)
